// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID        int32     `json:"id"`
	Owner     string    `json:"owner"`
	Balance   int32     `json:"balance"`
	Currency  string    `json:"currency"`
	CreatedAt time.Time `json:"created_at"`
}

type Entry struct {
	ID         int32         `json:"id"`
	AccountsID sql.NullInt32 `json:"accounts_id"`
	// Can be nagative
	Amount    int32     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int32         `json:"id"`
	FromAccountID sql.NullInt32 `json:"from_account_id"`
	ToAccountID   sql.NullInt32 `json:"to_account_id"`
	// Must be nagative
	Amount    int32     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}
